/**
 * ESLint flat config: the `@wordpress/scripts` defaults, plus what is specific to this plugin.
 */
const defaultConfig = require( '@wordpress/scripts/config/eslint.config.cjs' );

/**
 * Experimental WordPress APIs the plugin relies on, the same ones core blocks
 * use for the same purpose. They can change without notice: this list is what
 * to re-test against each WordPress release. Anything not listed is an error.
 */
const ALLOWED_UNSAFE_APIS = {
	'@wordpress/block-editor': [
		'__experimentalBlockVariationPicker',
		'__experimentalDateFormatPicker',
		'__experimentalGetSpacingClassesAndStyles',
		'__experimentalUseBlockPreview',
		'__experimentalUseBorderProps',
		'__experimentalUseColorProps',
	],
	'@wordpress/components': [
		'__experimentalHStack',
		// Show/hide button of the API key fields (settings page).
		'__experimentalInputControl',
		'__experimentalInputControlSuffixWrapper',
		'__experimentalItem',
		'__experimentalItemGroup',
		'__experimentalNumberControl',
		'__experimentalText',
		'__experimentalToolsPanel',
		'__experimentalToolsPanelItem',
		'__experimentalVStack',
	],
};

module.exports = [
	{
		ignores: [
			// Generated by SVGR (npm run build:icons): fix the template, not the output.
			'src/icons/components/**',
			'src/blocks/weather-report/icons/components/**',
			'src/icons/brand/components/**',
			'vendor-prefixed/**',
			// The presentation site built by npm run build:site.
			'_site/**',
			// Git worktrees of Claude Code: other checkouts of the plugin, with their own config.
			'.claude/**',
		],
	},
	...defaultConfig,
	{
		rules: {
			'@wordpress/no-unsafe-wp-apis': [ 'error', ALLOWED_UNSAFE_APIS ],
			// Every string goes to translate.wordpress.org under the plugin slug: no core strings, no missing domain.
			'@wordpress/i18n-text-domain': [
				'error',
				{ allowedTextDomain: 'elio-blocks' },
			],
			// `className` is already a block prop and a block attribute: a local variable of that name reads as one of them.
			'no-restricted-syntax': [
				'error',
				{
					selector: 'VariableDeclarator[id.name="className"]',
					message:
						'Write the class names in full where they are used: `className` is already a block prop and a block attribute.',
				},
			],
		},
	},
	{
		// Test helpers are test code too: dev-only imports. Vitest APIs are imported, not globals.
		files: [ 'src/test-utils/**/*.js', '**/test/**/*.js' ],
		languageOptions: {
			globals: {
				KeyboardEvent: 'readonly',
			},
		},
		rules: {
			'import/no-extraneous-dependencies': 'off',
		},
	},
];
