<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    '66cfd3a7190309803b5cc0fea03a4cdc' => $vendorDir . '/symfony/deprecation-contracts/function.php',
);
