<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'ElioBlocks\\Vendor\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'ElioBlocks\\Vendor\\Symfony\\Component\\VarExporter\\' => array($vendorDir . '/symfony/var-exporter'),
    'ElioBlocks\\Vendor\\Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'ElioBlocks\\Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
);
